# Generated by Django 6.1.1 on 2026-09-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('mobiles', 'Mobiles'), ('computers', 'computers'), ('electronics', 'Electronics'), ('vehicles', 'Vehicles'), ('property', 'Property'), ('fashion', 'Fashion'), ('furniture', 'Furniture'), ('musical_instruments', 'musical_instruments'), ('sports', 'sports'), ('books', 'Books'), ('toys', 'toys'), ('pets', 'pets'), ('jobs', 'Jobs'), ('services', 'Services'), ('other', 'Other')], default=('other', 'Other'), max_length=50),
            preserve_default=False,
        ),
    ]
