# Generated by Django 6.1.1 on 2026-10-01 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_listing_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('mobiles', 'Mobiles'), ('computers', 'computers'), ('electronics', 'Electronics'), ('vehicles', 'Vehicles'), ('property', 'Property'), ('fashion', 'Fashion'), ('furniture', 'Furniture'), ('musical_instruments', 'musical instruments'), ('sports', 'sports'), ('books', 'Books'), ('toys', 'toys'), ('pets', 'pets'), ('jobs', 'Jobs'), ('services', 'Services'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
